Check if the macro is defined prior its evaluation
Otherwise a compilation may end with following error:

/usr/include/libelf/libelf.h:28:5: error: "__LIBELF_INTERNAL__" is not
defined, evaluates to 0 [-Werror=undef]